<?xml version="1.0" encoding="utf-8"?><Database Name="MonitorizareEchipamente" Class="EquipmentDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=HEKARMEN\SQLEXPRESS;Initial Catalog=MonitorizareEchipamente;Integrated Security=True;Trust Server Certificate=True" SettingsObjectName="Proiect_ABD.Properties.Settings" SettingsPropertyName="MonitorizareEchipamenteConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Echipamente" Member="Echipamentes">
    <Type Name="Echipamente">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nume" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="UltimaActualizare" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Utilizatori" Member="Utilizatoris">
    <Type Name="Utilizatori">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NumeUtilizator" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Parola" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Rol" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>